-- ~/.dictate/config.lua — hand-edited defaults for dictate.lua
-- (generated by setup.sh; __PLACEHOLDERS__ are filled in during setup)
-- Mic choices made in the menu bar dropdown persist separately (hs.settings)
-- and take precedence over mic_mode / audio_device below.
return {
  hotkey            = "fn",           -- one of: "fn", "rightalt", "rightcmd", "rightctrl"
  model_path        = os.getenv("HOME") .. "/.dictate/models/ggml-small.en.bin",
  transcribe_mode   = "__TRANSCRIBE_MODE__", -- "server" (persistent, fast) or "cli" (fallback)
  server_bin        = "__SERVER_BIN__",
  cli_bin           = "__CLI_BIN__",
  server_port       = 12800,
  ffmpeg_bin        = "__FFMPEG_BIN__",
  mic_mode          = "auto",         -- "auto" (follow focused screen) or "fixed"
  audio_device      = { name = "__MIC_NAME__" },   -- fallback mic, matched by name
  min_duration_s    = 0.5,            -- discard shorter recordings
  max_duration_s    = 120,            -- hard cap; passed to ffmpeg -t
  language          = "en",
  paste_mode        = "pasteboard",   -- "pasteboard" (fast) or "keystrokes" (fallback)
  restore_delay_ms  = 300,            -- delay before pasteboard restore
  log_file          = os.getenv("HOME") .. "/.dictate/log.txt",
}
